version: "3"
services:

  nginx:
    image: zrongh/nginx:lastest
    ports:
     - "8001:8001"
     - "8000:80"
    # entrypoint: ["nginx", "-g", "daemon off;"]

  php:
    image: zrongh/zabbix_httpd:lastest
    environment:
      TARGET_IP: 
    ports:
     - "80:80"
    volumes:
    # mount /var/log/httpd to save log to local node
     - "/var/log/httpd:/var/log/httpd"
    # entrypoint: ["/usr/sbin/httpd"]
  mysql:
    image: zrongh/mysql:lastest
    ports:
     - "3306:3306"
    volumes:
     - "/var/lib/mysql:/var/lib/mysql"
